commands:
  custom:
    description: |
      Send custom message to Platypus instance
    parameters:
      instance:
        default: PLATYPUS_HOST
        description: Location of Platypus instance
        type: env_var_name
      job-name:
        default: CircleCI
        description: Job name
        type: string
      message:
        default: ""
        description: Custom message/status
        type: string
      secret-key:
        default: PLATYPUS_SECRET
        description: Auth key for Platypus instance
        type: env_var_name
    steps:
    - run: |-
        curl --header "X-PLATYPUS-AUTH: ${<< parameters.secret-key >>}" --header "X-PLATYPUS-TYPE: << parameters.job-name >>" --request "POST" "${<< parameters.instance >>}/poll" \
        -H "Content-type: application/json" -d '{"status": "<< parameters.message >>"}'
  finished:
    description: |
      Send custom message to Platypus instance
    parameters:
      instance:
        default: PLATYPUS_HOST
        description: Location of Platypus instance
        type: env_var_name
      job-name:
        default: CircleCI
        description: Job name
        type: string
      secret-key:
        default: PLATYPUS_SECRET
        description: Auth key for Platypus instance
        type: env_var_name
    steps:
    - run: |-
        curl --verbose  --header "X-PLATYPUS-AUTH: ${<< parameters.secret-key >>}" --header "X-PLATYPUS-TYPE: << parameters.job-name >>" --request "POST" "${<< parameters.instance >>}/poll" \
        -H "Content-type: application/json" -d '{"status": "finished"}'
  full-custom:
    description: |
      Send custom message to Platypus instance
    parameters:
      instance:
        default: PLATYPUS_HOST
        description: Location of Platypus instance
        type: env_var_name
      job-name:
        default: CircleCI
        description: Job name
        type: string
      message:
        default: '{}'
        description: JSON message/status
        type: string
      secret-key:
        default: PLATYPUS_SECRET
        description: Auth key for Platypus instance
        type: env_var_name
    steps:
    - run: |-
        curl --verbose  --header "X-PLATYPUS-AUTH: ${<< parameters.secret-key >>}" --header "X-PLATYPUS-TYPE: << parameters.job-name >>/poll" --request "POST" "${<< parameters.instance >>}" \
        -H "Content-type: application/json" -d '<< parameters.message >>'
  started:
    description: |
      Ping Platypus instance to notify of started job
    parameters:
      instance:
        default: PLATYPUS_HOST
        description: Location of Platypus instance
        type: env_var_name
      job-name:
        default: CircleCI
        description: Job name
        type: string
      secret-key:
        default: PLATYPUS_SECRET
        description: Auth key for Platypus instance
        type: env_var_name
    steps:
    - run: |-
        curl --header "X-PLATYPUS-AUTH: ${<< parameters.secret-key >>}" --header "X-PLATYPUS-TYPE: << parameters.job-name >>" --request "POST" "${<< parameters.instance >>}/poll" \
        -H "Content-type: application/json" -d '{"status": "started"}'
description: Talk to Platypus
version: 2.1

